## Python Fundamentals

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 

In [4]:
# version of pytorch
print(torch.__version__)
# this is the torch version running on cpu

2.6.0+cpu


## Create Tensors

#### Directly from data

In [ ]:
x = [[1,2],[3,4]]
x_tensor = torch.tensor(x) 
print(type(x_tensor))
print(x_tensor.dtype)
print(x_tensor)

<class 'torch.Tensor'>
torch.int64
tensor([[1, 2],
        [3, 4]])


In [39]:
scaler = torch.tensor(3)
print(scaler)
print(scaler.dtype)
print(scaler.ndim)
print(scaler.item())

tensor(3)
torch.int64
0
3


In [44]:
# vector 
vector = [1,2]
vector = torch.tensor(vector)
print(vector)
print(vector.ndim)
print(type(vector))
print(vector.dtype)
print(vector.shape)

tensor([1, 2])
1
<class 'torch.Tensor'>
torch.int64
torch.Size([2])


In [48]:
# matrix
matrix = torch.tensor([
    [1,2],
    [3,4]
])

print(matrix)
print(matrix.ndim)
print(matrix.shape)

tensor([[1, 2],
        [3, 4]])
2
torch.Size([2, 2])


In [58]:
# Tensor
tensor = torch.tensor([
    [
        [1,2],
        [2,4],
        [5,6]
    ]
])

print(tensor)
print(tensor.ndim)
print(tensor.shape)
print(tensor.tolist())

tensor([[[1, 2],
         [2, 4],
         [5, 6]]])
3
torch.Size([1, 3, 2])
[[[1, 2], [2, 4], [5, 6]]]


#### From A Numpy Array

In [25]:
np_data = np.array(x)
print("Numpy Array Type:",type(np_data))
np_tensor = torch.from_numpy(np_data)
print("Tensor Array Type:", type(np_tensor))
print("Tensor",np_tensor)


Numpy Array Type: <class 'numpy.ndarray'>
Tensor Array Type: <class 'torch.Tensor'>
Tensor tensor([[1, 2],
        [3, 4]])


#### Random tensor

In [81]:
shape = (2,3)
r_tensor = torch.rand(shape)  # generate number between zero and one
print(f"Random Tensor:\n\n{r_tensor}")

Random Tensor:

tensor([[0.0918, 0.0809, 0.7433],
        [0.2523, 0.5787, 0.1340]])


In [83]:
random_image_size = torch.rand(size=(224,224,3))
random_image_size

tensor([[[0.7884, 0.6507, 0.0583],
         [0.9768, 0.3674, 0.5166],
         [0.8108, 0.7516, 0.0702],
         ...,
         [0.4315, 0.5366, 0.7618],
         [0.6263, 0.5910, 0.6895],
         [0.3982, 0.2678, 0.2690]],

        [[0.7867, 0.8922, 0.6026],
         [0.2534, 0.4903, 0.6981],
         [0.5049, 0.4392, 0.1940],
         ...,
         [0.0167, 0.1929, 0.7710],
         [0.7703, 0.9094, 0.0585],
         [0.8356, 0.7628, 0.2683]],

        [[0.2019, 0.6981, 0.5451],
         [0.4395, 0.5509, 0.4010],
         [0.1824, 0.0383, 0.7465],
         ...,
         [0.9304, 0.0378, 0.3898],
         [0.8733, 0.7219, 0.6616],
         [0.4952, 0.5208, 0.8298]],

        ...,

        [[0.4788, 0.3103, 0.9184],
         [0.5859, 0.5897, 0.0343],
         [0.4692, 0.2437, 0.2586],
         ...,
         [0.7248, 0.9099, 0.4687],
         [0.4375, 0.9610, 0.6429],
         [0.2492, 0.8631, 0.3144]],

        [[0.0755, 0.3083, 0.4320],
         [0.8815, 0.1886, 0.3558],
         [0.

### Zero and Ones Tensor

In [92]:
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [95]:
zeros = torch.zeros(size=(3,3))
zeros
print(zeros.shape)
print(zeros.ndim)
print(zeros.device)

torch.Size([3, 3])
2
cpu


tensor([0, 1, 2, 3, 4])