## Python Fundamentals

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 

In [4]:
# version of pytorch
print(torch.__version__)
# this is the torch version running on cpu

2.6.0+cpu


## Create Tensors

#### Directly from data

In [ ]:
x = [[1,2],[3,4]]
x_tensor = torch.tensor(x) 
print(type(x_tensor))
print(x_tensor.dtype)
print(x_tensor)

<class 'torch.Tensor'>
torch.int64
tensor([[1, 2],
        [3, 4]])


In [39]:
scaler = torch.tensor(3)
print(scaler)
print(scaler.dtype)
print(scaler.ndim)
print(scaler.item())

tensor(3)
torch.int64
0
3


In [44]:
# vector 
vector = [1,2]
vector = torch.tensor(vector)
print(vector)
print(vector.ndim)
print(type(vector))
print(vector.dtype)
print(vector.shape)

tensor([1, 2])
1
<class 'torch.Tensor'>
torch.int64
torch.Size([2])


In [48]:
# matrix
matrix = torch.tensor([
    [1,2],
    [3,4]
])

print(matrix)
print(matrix.ndim)
print(matrix.shape)

tensor([[1, 2],
        [3, 4]])
2
torch.Size([2, 2])


In [58]:
# Tensor
tensor = torch.tensor([
    [
        [1,2],
        [2,4],
        [5,6]
    ]
])

print(tensor)
print(tensor.ndim)
print(tensor.shape)
print(tensor.tolist())

tensor([[[1, 2],
         [2, 4],
         [5, 6]]])
3
torch.Size([1, 3, 2])
[[[1, 2], [2, 4], [5, 6]]]


#### From A Numpy Array

In [25]:
np_data = np.array(x)
print("Numpy Array Type:",type(np_data))
np_tensor = torch.from_numpy(np_data)
print("Tensor Array Type:", type(np_tensor))
print("Tensor",np_tensor)


Numpy Array Type: <class 'numpy.ndarray'>
Tensor Array Type: <class 'torch.Tensor'>
Tensor tensor([[1, 2],
        [3, 4]])


#### Random tensor

In [81]:
shape = (2,3)
r_tensor = torch.rand(shape)  # generate number between zero and one
print(f"Random Tensor:\n\n{r_tensor}")

Random Tensor:

tensor([[0.0918, 0.0809, 0.7433],
        [0.2523, 0.5787, 0.1340]])


In [83]:
random_image_size = torch.rand(size=(224,224,3))
random_image_size

tensor([[[0.7884, 0.6507, 0.0583],
         [0.9768, 0.3674, 0.5166],
         [0.8108, 0.7516, 0.0702],
         ...,
         [0.4315, 0.5366, 0.7618],
         [0.6263, 0.5910, 0.6895],
         [0.3982, 0.2678, 0.2690]],

        [[0.7867, 0.8922, 0.6026],
         [0.2534, 0.4903, 0.6981],
         [0.5049, 0.4392, 0.1940],
         ...,
         [0.0167, 0.1929, 0.7710],
         [0.7703, 0.9094, 0.0585],
         [0.8356, 0.7628, 0.2683]],

        [[0.2019, 0.6981, 0.5451],
         [0.4395, 0.5509, 0.4010],
         [0.1824, 0.0383, 0.7465],
         ...,
         [0.9304, 0.0378, 0.3898],
         [0.8733, 0.7219, 0.6616],
         [0.4952, 0.5208, 0.8298]],

        ...,

        [[0.4788, 0.3103, 0.9184],
         [0.5859, 0.5897, 0.0343],
         [0.4692, 0.2437, 0.2586],
         ...,
         [0.7248, 0.9099, 0.4687],
         [0.4375, 0.9610, 0.6429],
         [0.2492, 0.8631, 0.3144]],

        [[0.0755, 0.3083, 0.4320],
         [0.8815, 0.1886, 0.3558],
         [0.

### Zero and Ones Tensor

In [98]:
ones = torch.ones(size=(3,4))
print(ones.dtype)
print(ones)

torch.float32
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [95]:
zeros = torch.zeros(size=(3,3))
zeros
print(zeros.shape)
print(zeros.ndim)
print(zeros.device)

torch.Size([3, 3])
2
cpu


### Create a range tensors and Tensor-like

In [102]:
x = torch.arange(10)
y = torch.arange(5,20)
z= torch.arange(10,100,5)
print(x)
print(y)
print(z)
print(z.shape)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])
tensor([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90, 95])
torch.Size([18])


In [106]:
# tensor-like method 
a = torch.ones_like(x).reshape(2,5)
print(a)

tensor([[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]])


In [109]:
a.shape

torch.Size([2, 5])

In [ ]:
float_32_tensor = torch.tensor(
    [3,2,4],
    dtype=torch.float32, # type of the tensor 
    device=None, # tensor is store on which device
    requires_grad=False # weather we have to find the gradients of this tensor or not 
    
    )
print(float_32_tensor.dtype)
print(float_32_tensor.device)
print(float_32_tensor.requires_grad)

torch.float32
cpu
False


In [127]:
float_16_tensor = float_32_tensor.type(torch.float16)

In [131]:
float_16_tensor

tensor([3., 2., 4.], dtype=torch.float16)

In [136]:
float_32_tensor.dtype

torch.float32

In [141]:
tensor_mul = float_16_tensor * float_32_tensor

In [142]:
tensor_mul.dtype

torch.float32

#### Attributes of a Tensor

In [147]:
random_tensor = torch.rand(2,4)
print(random_tensor)

print(f"\nshape: {random_tensor.shape}")
print(f"type: {random_tensor.dtype}")
print(f"device: {random_tensor.device}")

tensor([[0.9925, 0.1693, 0.4869, 0.1555],
        [0.3278, 0.4544, 0.3958, 0.2284]])

shape: torch.Size([2, 4])
type: torch.float32
device: cpu


In [153]:
torch.accelerator.is_available()

False

#### Operations on Tensors
Over 1200 tensor operations, including arithmetic, linear algebra, matrix manipulation (transposing, indexing, slicing), sampling and more are comprehensively described here.

Each of these operations can be run on the CPU and Accelerator such as CUDA, MPS, MTIA, or XPU. If you’re using Colab, allocate an accelerator by going to Runtime > Change runtime type > GPU.

By default, tensors are created on the CPU. We need to explicitly move tensors to the accelerator using .to method (after checking for accelerator availability). Keep in mind that copying large tensors across devices can be expensive in terms of time and memory!

#### Manipulation Tensor

In [180]:
# Adding of tensor
tensor_a = torch.arange(1,11)
tensor_b = torch.arange(11,21)


In [181]:
tensor_a + tensor_b

tensor([12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [182]:
# subtraction of tensor
tensor_a - tensor_b

tensor([-10, -10, -10, -10, -10, -10, -10, -10, -10, -10])

In [189]:
# multiplication of tensor element wise

tensor_a.reshape(2,5) * tensor_b.reshape(2,5)

tensor([[ 11,  24,  39,  56,  75],
        [ 96, 119, 144, 171, 200]])

In [226]:
torch.mul(tensor_a,3)

tensor([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [190]:
tensor_b, tensor_a

(tensor([11, 12, 13, 14, 15, 16, 17, 18, 19, 20]),
 tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]))

In [195]:
# tensor build in function/methods
torch.subtract(tensor_a,tensor_b)

tensor([-10, -10, -10, -10, -10, -10, -10, -10, -10, -10])

In [220]:
# multiplication of tensort 
# columns of first tensor = row of other tensor

tensor_one = torch.arange(1,13).reshape(2,6)
tensor_two = torch.arange(11,23).reshape(6,2)

In [221]:
tensor_one  

tensor([[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12]])

In [222]:
tensor_two

tensor([[11, 12],
        [13, 14],
        [15, 16],
        [17, 18],
        [19, 20],
        [21, 22]])

In [216]:
tensor_one @ tensor_two

tensor([[ 371,  392],
        [ 947, 1004]])

In [227]:
torch.matmul(tensor_one,tensor_two)

tensor([[ 371,  392],
        [ 947, 1004]])

In [230]:
tensor_two.shape

torch.Size([6, 2])

#### Tensor Aggression (Min, Max, Mean, Sum)

In [232]:
tensor_a = torch.arange(30,40)
tensor_a

tensor([30, 31, 32, 33, 34, 35, 36, 37, 38, 39])

In [238]:
print(f"min: {tensor_a.min()}")
print(f"max: {tensor_a.max()}")
print(f"mean: {tensor_a.mean(dtype=torch.float32)}")
print(f"min: {tensor_a.sum()}")

min: 30
max: 39
mean: 34.5
min: 345


In [241]:
print(f"mean: {tensor_a.type(torch.float32).mean()}")

mean: 34.5


In [246]:
# argmin and argmax
print(tensor_a)
print(tensor_a.argmax(),torch.argmax(tensor_a))

print(f"argmin: {tensor_a.argmin()}",torch.argmin(tensor_a))


tensor([30, 31, 32, 33, 34, 35, 36, 37, 38, 39])
tensor(9) tensor(9)
argmin: 0 tensor(0)


#### Reshaping,View, Stacking, Squeezing and unSqueezing 

In [254]:
# reshape 

tensor_price = torch.arange(1,10)
print(f"Before Reshape: {tensor_price}")

tensor_price_reshape = tensor_price.reshape(3,3)

print(f"\nTensor_Price Reshape: {tensor_price_reshape}")

Before Reshape: tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

Tensor_Price Reshape: tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


In [271]:
# share same original memory not copy the tensor
tensor_price_view = tensor_price.view(3,3)

In [265]:
tensor_price_view

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [266]:
tensor_price

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [269]:
tensor_price_view[0,0]=1000
tensor_price_view

tensor([[1000,    2,    3],
        [   4,    5,    6],
        [   7,    8,    9]])

In [270]:
tensor_price

tensor([1000,    2,    3,    4,    5,    6,    7,    8,    9])

In [276]:
# stacking in torch

x_tensor = torch.rand(2,3)
print(x_tensor)
print(x_tensor.ndim)

tensor([[0.5682, 0.2757, 0.6397],
        [0.2030, 0.8438, 0.3019]])
2


In [291]:
# dim 0
torch.stack((x_tensor,x_tensor))

tensor([[[0.5682, 0.2757, 0.6397],
         [0.2030, 0.8438, 0.3019]],

        [[0.5682, 0.2757, 0.6397],
         [0.2030, 0.8438, 0.3019]]])

In [280]:
torch.tensor([[[0.4266, 0.8334, 0.8515],
 [0.5160, 0.0867, 0.9786]],
[[0.4266, 0.8334, 0.8515],
 [0.5160, 0.0867, 0.9786]]])

tensor([[[0.4266, 0.8334, 0.8515],
         [0.5160, 0.0867, 0.9786]],

        [[0.4266, 0.8334, 0.8515],
         [0.5160, 0.0867, 0.9786]]])

In [297]:
# dim 1
torch.stack((x_tensor,x_tensor),dim=1)


tensor([[[0.5682, 0.2757, 0.6397],
         [0.5682, 0.2757, 0.6397]],

        [[0.2030, 0.8438, 0.3019],
         [0.2030, 0.8438, 0.3019]]])

In [299]:
torch.stack((x_tensor, x_tensor), dim=2)


tensor([[[0.5682, 0.5682],
         [0.2757, 0.2757],
         [0.6397, 0.6397]],

        [[0.2030, 0.2030],
         [0.8438, 0.8438],
         [0.3019, 0.3019]]])

In [302]:
# squeeze of tensor
x = torch.zeros(2, 1, 2, 1, 2)
x.shape

torch.Size([2, 1, 2, 1, 2])

In [304]:
x.squeeze().shape

torch.Size([2, 2, 2])

In [307]:
torch.squeeze(x,dim=0).shape

torch.Size([2, 1, 2, 1, 2])

In [308]:
torch.squeeze(x,dim=1).shape

torch.Size([2, 2, 1, 2])

In [313]:
tensor_a

tensor([30, 31, 32, 33, 34, 35, 36, 37, 38, 39])

In [ ]:
# unsqueeze of tensor 
torch.unsqueeze(tensor_a,dim=0)


torch.Size([1, 10])

In [320]:
torch.unsqueeze(tensor_a,dim=1).shape

torch.Size([10, 1])

In [325]:
# permute in torch

x = torch.randn(2, 3, 5)
print(x)

tensor([[[-0.7115,  1.7455,  0.0514, -0.1406,  0.5600],
         [ 1.1266, -0.7419,  0.3607,  1.1387, -0.3704],
         [-3.3526,  0.7225,  0.3599, -1.4835, -1.1324]],

        [[-2.0386, -0.2258,  0.5201, -1.1259, -0.4892],
         [ 0.1076, -0.1583,  1.7062,  1.8113,  0.7939],
         [ 1.2995,  0.9758, -0.2459,  0.4449,  0.7122]]])


In [326]:
torch.permute(x,(2,0,1))

tensor([[[-0.7115,  1.1266, -3.3526],
         [-2.0386,  0.1076,  1.2995]],

        [[ 1.7455, -0.7419,  0.7225],
         [-0.2258, -0.1583,  0.9758]],

        [[ 0.0514,  0.3607,  0.3599],
         [ 0.5201,  1.7062, -0.2459]],

        [[-0.1406,  1.1387, -1.4835],
         [-1.1259,  1.8113,  0.4449]],

        [[ 0.5600, -0.3704, -1.1324],
         [-0.4892,  0.7939,  0.7122]]])